### ISSUE TITLE
System fontname ios and android

### ISSUE THREAD

**Issue by muhammetsahin** [matteobortolazzo/HtmlLabelPlugin#9] opened 2018-01-16 14:12 UTC
Hi there,

How can we set system fontname for ios and android

![image](https://user-images.githubusercontent.com/2045788/34993127-774df58a-fae0-11e7-8b36-e774a7e1bf77.png)

-Font is wrong on the text in this screen (red square). Looks like Times New Roman?
Don’t know what you have used in all the other screens but this is not the same.

Thanks

**Comment by matteobortolazzo** [comment] 2018-01-16 16:17
The plugin doesn't override the font, I'll investigate.

**Comment by matteobortolazzo** [comment] 2018-01-28 19:04
My label and the standard label use the same font so I don't understand the issue, I'll close it for now

**Comment by castrojr913** [comment] 2018-01-31 03:34
@matteobortolazzo  I use the 1.0.4 version and It appears the texts with Time New Roman font and a smaller size on iOS. However, It works on Android perfectly (taking the default font-family and size correctly). Maybe, the cause of this issue is the description of this link: https://stackoverflow.com/questions/13126363/setting-default-font-size-while-loading-html-into-nstextview

**Comment by matteobortolazzo** [comment] 2018-01-31 08:36
Ok thanks I'll fix soon

**Comment by matteobortolazzo** [comment] 2018-02-03 09:10
I'm not able to test it on an iPhone so I trust you :)
I released [2.1.3](https://www.nuget.org/packages/Xam.Plugin.HtmlLabel/2.1.3) on nuget.
Could you test it?

**Comment by castrojr913** [comment] 2018-02-03 15:35
@matteobortolazzo Yes, I tested on a iPhone 6 SE with iOS 11.

**Comment by matteobortolazzo** [comment] 2018-02-03 20:38
Excellent, thank you again

**Closed by matteobortolazzo** 2018-02-03 20:38 UTC
